name: Build and Test EE
on: [pull_request, push]
jobs:
  build-and-test-ee:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - uses: actions/checkout@v2
      - name: Execute pipeline
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: true
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          VERSION: 7.13.18
