# Effective 2026-04-24, we no longer publish images to a public Docker Hub.
name: Build, test, and publish CE
on: [pull_request, push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_USR | NEXUS_USER;
            secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_PSW | NEXUS_PASS;
      - name: Build
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          NEXUS_PASS: ${{ steps.secrets.outputs.NEXUS_PASS }}
          NEXUS_USER: ${{ steps.secrets.outputs.NEXUS_USER }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
  build-and-test-arm:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: aws-arm-core-4-default
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_USR | NEXUS_USER;
            secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_PSW | NEXUS_PASS;
      - name: Build
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          NEXUS_PASS: ${{ steps.secrets.outputs.NEXUS_PASS }}
          NEXUS_USER: ${{ steps.secrets.outputs.NEXUS_USER }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
