name: Build and Test EE
on: [pull_request, workflow_dispatch]
jobs:
  build-and-test-ee:
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        DISTRO: [tomcat, wildfly, run]
        PLATFORM: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ matrix.PLATFORM != 'amd64' }}
        with:
          platforms: ${{ matrix.PLATFORM }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 300  # seconds
          max_attempts: 3
          command: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: true
          PLATFORM: ${{ matrix.PLATFORM }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: true
          PLATFORM: ${{ matrix.PLATFORM }}
