# Effective 2026-04-24, we no longer publish images to a public Docker Hub.
name: Build and test CE
on: [pull_request, push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
  build-and-test-arm:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: aws-arm-core-4-default
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
