# Effective 2026-04-24, we no longer publish images to a public Docker Hub.
name: Build, test, and publish CE
on: [pull_request, push, workflow_dispatch]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/nexus USER | NEXUS_USER;
            secret/data/products/cambpm/ci/nexus PASSWORD | NEXUS_PASS;
            secret/data/products/cambpm/ci/harbor username | HARBOR_USERNAME;
            secret/data/products/cambpm/ci/harbor password | HARBOR_PASSWORD;
      - name: Login to Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: registry.camunda.cloud
          username: ${{ steps.secrets.outputs.HARBOR_USERNAME }}
          password: ${{ steps.secrets.outputs.HARBOR_PASSWORD }}
      - name: Build
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          NEXUS_PASS: ${{ steps.secrets.outputs.NEXUS_PASS }}
          NEXUS_USER: ${{ steps.secrets.outputs.NEXUS_USER }}
          PUSH_REGISTRY: ${{ github.event_name != 'pull_request' && 'registry.camunda.cloud/team-cambpm' || '' }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
  build-and-test-arm:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: aws-arm-core-4-default
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/nexus USER | NEXUS_USER;
            secret/data/products/cambpm/ci/nexus PASSWORD | NEXUS_PASS;
            secret/data/products/cambpm/ci/harbor username | HARBOR_USERNAME;
            secret/data/products/cambpm/ci/harbor password | HARBOR_PASSWORD;
      - name: Login to Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: registry.camunda.cloud
          username: ${{ steps.secrets.outputs.HARBOR_USERNAME }}
          password: ${{ steps.secrets.outputs.HARBOR_PASSWORD }}
      - name: Build
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          NEXUS_PASS: ${{ steps.secrets.outputs.NEXUS_PASS }}
          NEXUS_USER: ${{ steps.secrets.outputs.NEXUS_USER }}
          PUSH_REGISTRY: ${{ github.event_name != 'pull_request' && 'registry.camunda.cloud/team-cambpm' || '' }}
      - name: Test
        run: ./test.sh
        working-directory: test
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false

  create-manifests-ce:
    if: github.event_name != 'pull_request'
    needs: [build-and-test, build-and-test-arm]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/data/products/cambpm/ci/harbor username | HARBOR_USERNAME;
            secret/data/products/cambpm/ci/harbor password | HARBOR_PASSWORD;
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: registry.camunda.cloud
          username: ${{ steps.secrets.outputs.HARBOR_USERNAME }}
          password: ${{ steps.secrets.outputs.HARBOR_PASSWORD }}
      - name: Create multi-arch manifests
        run: ./create-manifests.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: false
          PUSH_REGISTRY: registry.camunda.cloud/team-cambpm

