name: Build and Test EE

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Camunda enterprise version to be tested'
      snapshot:
        description: 'Whether the version is a snapshot'
  pull_request:

jobs:
  build-and-test-ee:
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        DISTRO: [tomcat, wildfly, run]
    steps:
      - uses: actions/checkout@v3
      - name: Execute pipeline
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: true
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
