name: Build and Test
on: [pull_request, push]
jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - DISTRO: "tomcat"
            EE: "false"
          - DISTRO: "wildfly"
            EE: "false"
          - DISTRO: "run"
            EE: "false"
    steps:
      - uses: actions/checkout@v2
      - name: Execute pipeline
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: ${{ matrix.EE }}
