name: Publish CE image
on:
  push:
    branches:
      - next
      - 7.[0-9]+ # not real regex (https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)
jobs:
  publish-ce-image:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - DISTRO: "tomcat"
            EE: "false"
          - DISTRO: "wildfly"
            EE: "false"
          - DISTRO: "run"
            EE: "false"
    steps:
      - uses: actions/checkout@v2
      - name: Release CE docker image
        run: ./release.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: ${{ matrix.EE }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKER_HUB_USERNAME:  ${{ secrets.DOCKER_HUB_USERNAME }}
